version: 2

sources:
  - name: raw_data
    description: "Raw data sources for NYC DE"
    database: de-camp-01 # in BQ this is the Project ID
    schema: nytaxi # in BQ this is dataset name
    tables:
      - name: yellow_tripdata
      - name: green_tripdata

