user:
  outputs:
    JPersonalCreds:
      job_execution_timeout_seconds: 300
      keyfile_json:
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        auth_uri: https://accounts.google.com/o/oauth2/auth
        client_email: terraform-de-runner@de-camp-01.iam.gserviceaccount.com
        client_id: '105450517045053175223'
        client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/terraform-de-runner%40de-camp-01.iam.gserviceaccount.com
        private_key: '-----BEGIN PRIVATE KEY-----

          MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCTOCXYkoGZrd6e

          l2sF83HNpDJzSvZdAqJFKq69MwPYaBIOqlGkpKi+6GYgXidANmR8WmQgNgvW03kB

          Fid+jf7YgCHzScuKLJzrUTr/eMu67gdwwQnigMy/6sautRYDRB2lweKbSsbNBWhH

          vDP4FezJiypVDOh978cY4akg+RzIumYAnpQOFBc8NSdyUKaYeiFvcuIa4Ik0foJf

          r5r7uEsa0MmzrgG2iFXDqgsa15/DZW23e5RHmJJHju8YHIpLCaeb7riyrUO3ntKZ

          dxN1hVL7Iv+fGjHOqGaZEycgJMfmFEC4TjLdZ8ZqhZ8fIyzr2myAE6UOVHr6gVDP

          eiOtyAwvAgMBAAECggEAOAvqLJcqC82rsQjIT82sh7N5GXdyb1pvWJG1UIY5cou8

          RCUHS/z72SI0ryHpI4MRol3vPGwW+cQsjwNWKdH5MYcmZa60dHgjjVqxcU0VkqbH

          4l87WiXazT2eQijipn+qIc68bI59PNRQLO8zgcEnEluO1C5D3J4KWCig8NKl6Kyp

          8z1fznwuHvBwA8ISFC96mCr+5Kg1fksQcNjAEasVWtRSjgj+vrkAzMyvuvcOTIuI

          PUXcUw9wks8czA8vaYiUt2spIOBoslbPyNREQxiTi7L5Lebbcf4GeeHFyEpsMLga

          9InhawGiThwXfQ0EH/tVJQ5+FAqmyvR/oaADgle5cQKBgQDKUy3YLX10QgbzPoH2

          DJB1ZC2/h1r6ructUeeYcaDDP4VOX14aPjI3L21P3ooAi+XqSztHWA6QqNLgqcti

          8U7P0qbO9h1p8qxBaXncHn7jY3UPnWXOZQAQzce9saXAPwdksQ2NQHXdFqeXiX5M

          0C9X1/9Fv0wN4OfsysaaD/cOUwKBgQC6Rn5EXTu+Irlt7RIKlxnt9hN2l8yemu1j

          1HQsDJgLIXBnyiYIgwfLp9HPsthfTD8hfPmMUNTusnVizSpalYx7upbPkmVbIFUw

          o79vx4NMw/Vh/fgtEHVA4lZP3JwqMsEj4uv0//f+I3mATFEy9jkTIk5/LCPAa2H/

          lk0/wfD3NQKBgG1SzK7GxccP9llxKSAeYeBMpTuck9hosZmXbCC/JTLbG9jhRyO+

          /7s58UL66G6rKSyUQg+m0RfxYSDsHm30HbXGCURDUFlzOwiNSb9a6w1LLHGnht8j

          TAnIZ2lkmD9szz3lPYFZl1ZDa4NCU/CFfU9l8xVo7FuDb05Ps0iD3+bpAoGAZi7r

          bzcx4bCMxfeJsROIntghfynwjoTwepX+EHfsJBb44Yar7HlsmlR6LRSvyz85VnaH

          MmjZFgQBjux7MmvdP7ZwqndlcGLBOMhq6LeqmD7a6iF2tcnUeH5w2KhtZlynRLdj

          tud/tALj0PSMioc1cgCczPh6uEBv5tQdlj8en40CgYB63x7uohf0rr8GI2qPMIpj

          oQbOCAhk69MEbiAVbRAam8cztBnO2QhPH58qphayPPSyx0TtDnyFiwxQOD9Fhj9H

          AyHLGPSQLJ2Od4l0ukt1FyL6WxiJRoGiSnFfNpbS0kZvaDfnSgrrLE68d3GUvmO/

          /4mMR7WdJ5nCYnXSl45VfA==

          -----END PRIVATE KEY-----

          '
        private_key_id: aea8c879405ed6e341c1e226724f0dd71d6ac7de
        project_id: de-camp-01
        token_uri: https://oauth2.googleapis.com/token
        type: service_account
      location: us-central1
      method: service-account-json
      project: de-camp-01
      schema: dbt_prod
      scopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/drive
      - https://www.googleapis.com/auth/userinfo.email
      target_name: JPersonalCreds
      threads: 6
      type: bigquery
  target: JPersonalCreds
